using System;
using System.Collections.Generic;
using System.Text;

namespace Hydrogen.FIX
{
    public class AdjustedPositionReport
    {
        public static readonly FieldSpec[] Schema = new FieldSpec[]
        {
            FIXTags.BeginString,
            FIXTags.BodyLength,
            FIXTags.MsgType,
            FIXTags.ApplVerID,
            FIXTags.CstmApplVerID,
            FIXTags.SenderCompID,
            FIXTags.TargetCompID,
            FIXTags.OnBehalfOfCompID,
            FIXTags.DeliverToCompID,
            FIXTags.SecureDataLen,
            FIXTags.SecureData,
            FIXTags.MsgSeqNum,
            FIXTags.SenderSubID,
            FIXTags.SenderLocationID,
            FIXTags.TargetSubID,
            FIXTags.TargetLocationID,
            FIXTags.OnBehalfOfSubID,
            FIXTags.OnBehalfOfLocationID,
            FIXTags.DeliverToSubID,
            FIXTags.DeliverToLocationID,
            FIXTags.PossDupFlag,
            FIXTags.PossResend,
            FIXTags.SendingTime,
            FIXTags.OrigSendingTime,
            FIXTags.XmlDataLen,
            FIXTags.XmlData,
            FIXTags.MessageEncoding,
            FIXTags.LastMsgSeqNumProcessed,
            FIXTags.NoHops,
            FIXTags.HopCompID,
            FIXTags.HopSendingTime,
            FIXTags.HopRefID,
            FIXTags.PosMaintRptID,
            FIXTags.PosReqType,
            FIXTags.ClearingBusinessDate,
            FIXTags.SettlSessID,
            FIXTags.PosMaintRptRefID,
            FIXTags.NoPartyIDs,
            FIXTags.PartyID,
            FIXTags.PartyIDSource,
            FIXTags.PartyRole,
            FIXTags.NoPartySubIDs,
            FIXTags.PartySubID,
            FIXTags.PartySubIDType,
            FIXTags.NoPositions,
            FIXTags.PosType,
            FIXTags.LongQty,
            FIXTags.ShortQty,
            FIXTags.PosQtyStatus,
            FIXTags.QuantityDate,
            FIXTags.NoNestedPartyIDs,
            FIXTags.NestedPartyID,
            FIXTags.NestedPartyIDSource,
            FIXTags.NestedPartyRole,
            FIXTags.NoNestedPartySubIDs,
            FIXTags.NestedPartySubID,
            FIXTags.NestedPartySubIDType,
            FIXTags.SettlPrice,
            FIXTags.PriorSettlPrice,
            FIXTags.SignatureLength,
            FIXTags.Signature,
            FIXTags.CheckSum,
        };
    }
}
