using System;
using System.Collections.Generic;
using System.Text;

namespace Hydrogen.FIX
{
    public class ConfirmationRequest
    {
        public static readonly FieldSpec[] Schema = new FieldSpec[]
        {
            FIXTags.BeginString,
            FIXTags.BodyLength,
            FIXTags.MsgType,
            FIXTags.ApplVerID,
            FIXTags.CstmApplVerID,
            FIXTags.SenderCompID,
            FIXTags.TargetCompID,
            FIXTags.OnBehalfOfCompID,
            FIXTags.DeliverToCompID,
            FIXTags.SecureDataLen,
            FIXTags.SecureData,
            FIXTags.MsgSeqNum,
            FIXTags.SenderSubID,
            FIXTags.SenderLocationID,
            FIXTags.TargetSubID,
            FIXTags.TargetLocationID,
            FIXTags.OnBehalfOfSubID,
            FIXTags.OnBehalfOfLocationID,
            FIXTags.DeliverToSubID,
            FIXTags.DeliverToLocationID,
            FIXTags.PossDupFlag,
            FIXTags.PossResend,
            FIXTags.SendingTime,
            FIXTags.OrigSendingTime,
            FIXTags.XmlDataLen,
            FIXTags.XmlData,
            FIXTags.MessageEncoding,
            FIXTags.LastMsgSeqNumProcessed,
            FIXTags.NoHops,
            FIXTags.HopCompID,
            FIXTags.HopSendingTime,
            FIXTags.HopRefID,
            FIXTags.ConfirmReqID,
            FIXTags.ConfirmType,
            FIXTags.NoOrders,
            FIXTags.ClOrdID,
            FIXTags.OrderID,
            FIXTags.SecondaryOrderID,
            FIXTags.SecondaryClOrdID,
            FIXTags.ListID,
            FIXTags.NoNested2PartyIDs,
            FIXTags.Nested2PartyID,
            FIXTags.Nested2PartyIDSource,
            FIXTags.Nested2PartyRole,
            FIXTags.NoNested2PartySubIDs,
            FIXTags.Nested2PartySubID,
            FIXTags.Nested2PartySubIDType,
            FIXTags.OrderQty,
            FIXTags.OrderAvgPx,
            FIXTags.OrderBookingQty,
            FIXTags.AllocID,
            FIXTags.SecondaryAllocID,
            FIXTags.IndividualAllocID,
            FIXTags.TransactTime,
            FIXTags.AllocAccount,
            FIXTags.AllocAcctIDSource,
            FIXTags.AllocAccountType,
            FIXTags.Text,
            FIXTags.EncodedTextLen,
            FIXTags.EncodedText,
            FIXTags.SignatureLength,
            FIXTags.Signature,
            FIXTags.CheckSum,
        };
    }
}
