using System;
using System.Collections.Generic;
using System.Text;

namespace Hydrogen.FIX
{
    public class ListStatus
    {
        public static readonly FieldSpec[] Schema = new FieldSpec[]
        {
            FIXTags.BeginString,
            FIXTags.BodyLength,
            FIXTags.MsgType,
            FIXTags.ApplVerID,
            FIXTags.CstmApplVerID,
            FIXTags.SenderCompID,
            FIXTags.TargetCompID,
            FIXTags.OnBehalfOfCompID,
            FIXTags.DeliverToCompID,
            FIXTags.SecureDataLen,
            FIXTags.SecureData,
            FIXTags.MsgSeqNum,
            FIXTags.SenderSubID,
            FIXTags.SenderLocationID,
            FIXTags.TargetSubID,
            FIXTags.TargetLocationID,
            FIXTags.OnBehalfOfSubID,
            FIXTags.OnBehalfOfLocationID,
            FIXTags.DeliverToSubID,
            FIXTags.DeliverToLocationID,
            FIXTags.PossDupFlag,
            FIXTags.PossResend,
            FIXTags.SendingTime,
            FIXTags.OrigSendingTime,
            FIXTags.XmlDataLen,
            FIXTags.XmlData,
            FIXTags.MessageEncoding,
            FIXTags.LastMsgSeqNumProcessed,
            FIXTags.NoHops,
            FIXTags.HopCompID,
            FIXTags.HopSendingTime,
            FIXTags.HopRefID,
            FIXTags.ListID,
            FIXTags.ListStatusType,
            FIXTags.NoRpts,
            FIXTags.ListOrderStatus,
            FIXTags.RptSeq,
            FIXTags.ListStatusText,
            FIXTags.EncodedListStatusTextLen,
            FIXTags.EncodedListStatusText,
            FIXTags.TransactTime,
            FIXTags.TotNoOrders,
            FIXTags.LastFragment,
            FIXTags.NoOrders,
            FIXTags.ClOrdID,
            FIXTags.SecondaryClOrdID,
            FIXTags.CumQty,
            FIXTags.OrdStatus,
            FIXTags.WorkingIndicator,
            FIXTags.LeavesQty,
            FIXTags.CxlQty,
            FIXTags.AvgPx,
            FIXTags.OrdRejReason,
            FIXTags.Text,
            FIXTags.EncodedTextLen,
            FIXTags.EncodedText,
            FIXTags.SignatureLength,
            FIXTags.Signature,
            FIXTags.CheckSum,
        };
    }
}
