using System;
using System.Collections.Generic;
using System.Text;

namespace Hydrogen.FIX
{
    public class SettlementInstructionRequest
    {
        public static readonly FieldSpec[] Schema = new FieldSpec[]
        {
            FIXTags.BeginString,
            FIXTags.BodyLength,
            FIXTags.MsgType,
            FIXTags.ApplVerID,
            FIXTags.CstmApplVerID,
            FIXTags.SenderCompID,
            FIXTags.TargetCompID,
            FIXTags.OnBehalfOfCompID,
            FIXTags.DeliverToCompID,
            FIXTags.SecureDataLen,
            FIXTags.SecureData,
            FIXTags.MsgSeqNum,
            FIXTags.SenderSubID,
            FIXTags.SenderLocationID,
            FIXTags.TargetSubID,
            FIXTags.TargetLocationID,
            FIXTags.OnBehalfOfSubID,
            FIXTags.OnBehalfOfLocationID,
            FIXTags.DeliverToSubID,
            FIXTags.DeliverToLocationID,
            FIXTags.PossDupFlag,
            FIXTags.PossResend,
            FIXTags.SendingTime,
            FIXTags.OrigSendingTime,
            FIXTags.XmlDataLen,
            FIXTags.XmlData,
            FIXTags.MessageEncoding,
            FIXTags.LastMsgSeqNumProcessed,
            FIXTags.NoHops,
            FIXTags.HopCompID,
            FIXTags.HopSendingTime,
            FIXTags.HopRefID,
            FIXTags.SettlInstReqID,
            FIXTags.TransactTime,
            FIXTags.NoPartyIDs,
            FIXTags.PartyID,
            FIXTags.PartyIDSource,
            FIXTags.PartyRole,
            FIXTags.NoPartySubIDs,
            FIXTags.PartySubID,
            FIXTags.PartySubIDType,
            FIXTags.AllocAccount,
            FIXTags.AllocAcctIDSource,
            FIXTags.Side,
            FIXTags.Product,
            FIXTags.SecurityType,
            FIXTags.CFICode,
            FIXTags.SettlCurrency,
            FIXTags.EffectiveTime,
            FIXTags.ExpireTime,
            FIXTags.LastUpdateTime,
            FIXTags.StandInstDbType,
            FIXTags.StandInstDbName,
            FIXTags.StandInstDbID,
            FIXTags.SignatureLength,
            FIXTags.Signature,
            FIXTags.CheckSum,
        };
    }
}
